### ISSUE TITLE
Drop doesn't drop ENUMs in postgres

### ISSUE THREAD

**Issue by ovadbar** [golang-migrate/migrate#478] opened 2020-11-19 19:43 UTC
**Describe the Bug**
Drop doesn't drop ENUMs in postgres

**Steps to Reproduce**
1. Create an up file with a `CREATE TYPE AS ENUM` statement
2. Run `migrate up`
3. Run `migrate drop`
4. Check to see if types still exist

**Expected Behavior**
Types should not exist

**Migrate Version**
v4.12.2

**Loaded Source Drivers**
Source drivers: file, s3, github, github-ee, gitlab, go-bindata, godoc-vfs, gcs

**Loaded Database Drivers**
Database drivers: cockroach, cockroachdb, mongodb, postgres, clickhouse, postgresql, spanner, firebird, mongodb+srv, stub, sqlserver, cassandra, crdb-postgres, firebirdsql, mysql, neo4j, redshift

**Go Version**
go version go1.15.3 darwin/amd64

**Stacktrace**
N/A
**Additional context**
See pull request https://github.com/golang-migrate/migrate/pull/477

**Comment by dhui** [comment] 2020-11-20 01:06
Duplicate of https://github.com/golang-migrate/migrate/issues/193

**Closed by dhui** 2020-11-20 01:06 UTC
Labels: duplicate
