### ISSUE TITLE
Unable to download the CLI

### ISSUE THREAD

**Issue by pablote** [golang-migrate/migrate#289] opened 2019-10-03 23:43 UTC
**Describe the Bug**
Unable to download the CLI using the "CLI documentation" instructions

**Steps to Reproduce**
```
go get -tags 'clickhouse' -u github.com/golang-migrate/migrate/cmd/migrate  
go: finding github.com/golang-migrate/migrate/cmd latest
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go get github.com/golang-migrate/migrate/cmd/migrate: module github.com/golang-migrate/migrate@upgrade (v3.5.4+incompatible) found, but does not contain package github.com/golang-migrate/migrate/cmd/migrate
```

**Expected Behavior**
CLI installed

**Go Version**
go version go1.13.1 darwin/amd64

**Comment by Jerome1337** [comment] 2019-10-07 13:26
Same problem today, this seems to work randomly

**Comment by Jerome1337** [comment] 2019-10-07 14:19
@pablote The README entry is not correct, follow this instructions https://github.com/golang-migrate/migrate/pull/257#issuecomment-526949205

**Comment by dhui** [comment] 2019-10-08 03:55
If you have a way to reproduce the issue, we can work on a fix. So far, I've been unable to reproduce the issue in a docker container.

Closing this issue in favor of the open PR.

**Closed by dhui** 2019-10-08 03:55 UTC
