### ISSUE TITLE
prevent to redeploy a modified file thanks to checksum of files already deployed on Cassandra

### ISSUE THREAD

**Issue by azraino** [golang-migrate/migrate#389] opened 2020-05-13 16:47 UTC
On Flyway there is a mechanism that generate a checksum of each file deployed on database. 

The checksum is stored on dedicated table and when a new migration is processed, a pre-step compare each checksum of files with the one on database. Then if there is any change the migration is simply broken and the program end.

I think that would be great if we can have the same mechanism on migrate mainly for Cassandra.

Thank you very much.

**Comment by dhui** [comment] 2020-05-13 17:14
Duplicate of https://github.com/golang-migrate/migrate/issues/310
Closing this to consolidate discussions

**Closed by dhui** 2020-05-13 17:14 UTC
Labels: duplicate
