### ISSUE TITLE
Suuport for Firebird SQL

### ISSUE THREAD

**Issue by micakovic** [golang-migrate/migrate#49] opened 2018-06-04 19:07 UTC
Any plans on supporting Firebird SQL?

https://github.com/nakagami/firebirdsql 
works well with 
https://golang.org/pkg/database/sql/

**Comment by dhui** [comment] 2018-06-04 23:14
I'm not planning on adding support myself but feel free to open a PR with tests

**Comment by kmuratov** [comment] 2019-03-15 20:25
Please review it
Added Firebird support https://github.com/golang-migrate/migrate/pull/191

**Comment by kmuratov** [comment] 2019-04-17 10:38
This issue can be closed now (https://github.com/golang-migrate/migrate/tree/master/database/firebird)

**Comment by dhui** [comment] 2019-04-17 18:16
Firebird is now supported in [v4.3.0](https://github.com/golang-migrate/migrate/releases/tag/v4.3.0)
This issue is resolved, but the Firebird tests are a bit flakey. e.g. there are intermittent failures.
Not sure if there's a bug with the Go client connecting to the DB or an issue w/ the Firebird docker image.

**Comment by kmuratov** [comment] 2019-04-23 12:11
This bug might be related to https://github.com/jacobalberty/firebird-docker/issues/33

**Comment by dhui** [comment] 2019-04-26 20:37
Since Firebird is creating a lot of problems with tests, I'm going to remove official support for it until the issue is resolved.

This means that:
1. Shipped assets (namely the CLI) won't have Firebird support built-in including:
    * Docker images
    * Binaries on Github release page
    * Binaries on PackageCloud
1. Tests won't run against Firebird

So for now, if you want Firebird support, you'll need need to build the migrate CLI yourself. There are also no guarantees that the integration will work since we're not testing with Firebird.

**Comment by jacobalberty** [comment] 2019-10-12 02:22
> This bug might be related to [jacobalberty/firebird-docker#33](https://github.com/jacobalberty/firebird-docker/issues/33)

@kmuratov I fixed and closed that issue last night. I'm curious to know if it fixed the test flakiness for you guys.

**Comment by dhui** [comment] 2019-10-12 22:12
@jacobalberty I doubt that your fix will address the issues we've been seeing as `FIREBIRD_DATABASE`, `FIREBIRD_USER`, and `FIREBIRD_PASSWORD` are all specified: https://github.com/golang-migrate/migrate/blob/v4.6.2/database/firebird/firebird_test.go#L35

**Comment by jacobalberty** [comment] 2019-10-14 05:32
@dhui  there were two fixes, one for specifying `FIREBIRD_DATABASE` without `FIREBIRD_USER` and `FIREBIRD_PASSWORD`, the other was it attempting to continue initialization before firebird had come up, see jacobalberty/firebird-docker@2ff3e3b43060f36869867708dbb4f0690fc5eb0f

**Comment by dhui** [comment] 2019-10-14 05:58
The last 2 CI builds didn't have any issues with Firebird, so that's looking good.
Once we have a few more successful builds, we can add official support for Firebird back to migrate!

**Comment by dhui** [comment] 2019-10-22 07:55
Fixed in [v4.7.0](https://github.com/golang-migrate/migrate/releases/tag/v4.7.0)

**Closed by dhui** 2019-10-22 07:55 UTC
Labels: enhancement, help wanted
