### ISSUE TITLE
mysql database registered twice

### ISSUE THREAD

**Issue by mdestagnol** [golang-migrate/migrate#83] opened 2018-08-03 19:53 UTC
**Step to reproduce**
Execute the sample code of this page: https://github.com/golang-migrate/migrate/tree/master/database/mysql

**Output**
It gives the following error:

```
panic: sql: Register called twice for driver mysql

goroutine 1 [running]:
database/sql.Register(0x127dc81, 0x5, 0x12a7a20, 0x13d2508)
	/usr/local/Cellar/go/1.10.3/libexec/src/database/sql/sql.go:50 +0x1a4
github.com/golang-migrate/migrate/vendor/github.com/go-sql-driver/mysql.init.0()
	/Users/martin/go/src/github.com/golang-migrate/migrate/vendor/github.com/go-sql-driver/mysql/driver.go:168 +0x5c
exit status 2
```

**Root cause**
The _migrate/database/mysql_ package uses _github.com/go-sql-driver/mysql_ which already registers the "mysql" driver. So when _migrate/database/mysql_ tries to register it as well, it creates this error.

**Comment by mdestagnol** [comment] 2018-08-03 20:14
**Question**
Should the registration of mysql driver by migrate be removed? I don't see why it's here in the first place, but I can't execute the test to make sure it doesn't brake anything (they require a docker install).

**Comment by dhui** [comment] 2018-08-07 01:29
I'm not having any issues building and running the example code for the MySQL db driver.

What's your "example" code look like? Are you using `import _ "github.com/go-sql-driver/mysql"` instead of `import "github.com/go-sql-driver/mysql"`

**Comment by mdestagnol** [comment] 2018-08-07 04:37
Weird. I've just tried again and I still have the error. I simply copy paste this example:

```
package main

import (
    "database/sql"
    
    _ "github.com/go-sql-driver/mysql"
    "github.com/golang-migrate/migrate"
    "github.com/golang-migrate/migrate/database/mysql"
    _ "github.com/golang-migrate/migrate/source/file"
)

func main() {
    db, _ := sql.Open("mysql", "user:password@tcp(host:port)/dbname?multiStatements=true")
    driver, _ := mysql.WithInstance(db, &mysql.Config{})
    m, _ := migrate.NewWithDatabaseInstance(
        "file:///migrations",
        "mysql", 
        driver,
    )
    
    m.Steps(2)
}
```

And I run it using a simple "go run main.go" command. You don't have the same problem?

**Comment by glaslos** [comment] 2018-08-22 08:46
The issue is not the error handling but both migrate and the [mysql](https://github.com/go-sql-driver/mysql/blob/99ff426eb706cffe92ff3d058e168b278cabf7c7/driver.go#L164) driver calling `sql.Register("mysql", &MySQLDriver{})` in an `init()` function:
https://github.com/golang-migrate/migrate/blob/beb09d85faffcee526b16ed19dea30c1dd843578/database/mysql/mysql.go#L27-L29
This should probably not happen in migrate in the case where you are using `NewWithDatabaseInstance` as it can be assumed that the db is already registered.

**Comment by glaslos** [comment] 2018-08-22 09:32
FYI I had the same issue with cockroachdb. Making sure I only had `migrate/database/cockroachdb` in my vendor folder solved the issue (`migrate/database/postgres` was causing the issue for me).

**Comment by dhui** [comment] 2018-08-22 09:54
> The issue is not the error handling but both migrate and the mysql driver calling sql.Register("mysql", &MySQLDriver{}) in an init() function:

This is incorrect. `database.Register()` registers the migrate mysql driver with migrate where as `sql.Register()` registers the sql driver with database/sql

> FYI I had the same issue with cockroachdb. Making sure I only had migrate/database/cockroachdb in my vendor folder solved the issue (migrate/database/postgres was causing the issue for me).

Not sure how this fixed the issue for you since each package's `init()` functions are [only called once](https://golang.org/doc/effective_go.html#init) and in a [well defined order](https://golang.org/ref/spec#Package_initialization), so even though both packages import lib/pq, the postgres sql driver should only be registered against database/sql once

**Comment by glaslos** [comment] 2018-08-22 11:13
Thanks for the clarification. I assume it has to do with me using [sqlx](https://github.com/jmoiron/sqlx) instead of pq directly.

**Comment by dhui** [comment] 2018-08-23 07:59
@glaslos 
> I assume it has to do with me using sqlx instead of pq directly.

I doubt it. sqlx [doesn't interact with any database/sql driver directly](https://godoc.org/github.com/jmoiron/sqlx?imports) and instead uses the database/sql/driver interface.

**Comment by dmmulroy** [comment] 2018-10-02 15:31
I'm also having this issue bot for postgres.  I'm getting:

```
panic: sql: Register called twice for driver postgres

goroutine 1 [running]:
database/sql.Register(0xbb73c7, 0x8, 0xc40920, 0xfe3aa0)
        /home/dmmulroy/go_versions/1.10.3/src/database/sql/sql.go:50 +0x1a4
github.com/golang-migrate/migrate/vendor/github.com/lib/pq.init.0()
        /home/dmmulroy/dev/repos/go/src/github.com/golang-migrate/migrate/vendor/github.com/lib/pq/conn.go:49 +0x5c
```

**Comment by dhui** [comment] 2018-10-03 05:19
@dmmulroy Can you share the code that reproduces the issue?
I didn't have issues w/ a modified version (only updated path and connection string for my setup) of @mdestagnol's code.

**Comment by dmmulroy** [comment] 2018-10-05 12:41
I ended up resolving the issue by completely removing golang-migrate from my vendor directory and re-pulling it in at version 3.5.1.  
Here is the code: S.DB is of type *sqlx.DB
```go
func (s *Server) migrateDatabase() error {
	driver, err := postgres.WithInstance(s.DB.DB, &postgres.Config{MigrationsTable: s.Config.DatabaseMigrationsTable})

	if err != nil {
		return err
	}

	m, err := migrate.NewWithDatabaseInstance(databaseMigrationsDirectory, "postgres", driver)

	if err != nil {
		return err
	}

	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return err
	}

	return nil

}
```

**Comment by dhui** [comment] 2018-10-16 07:09
Closing for now since it doesn't seem like anyone is still experiencing this. If steps to reproduce the issue are posted, I'll reopen this issue.

**Closed by dhui** 2018-10-16 07:09 UTC

**Comment by igor-pgmt** [comment] 2019-08-08 21:56
I have the sane error. I'm using mssql:

`    import (
	"database/sql"
	 _ "github.com/denisenkom/go-mssqldb"
	"github.com/golang-migrate/migrate"
	"github.com/golang-migrate/migrate/database/sqlserver"
// ...
)

// ...

	instance, err := sqlserver.WithInstance(db.DB, &sqlserver.Config{"MYDB.Myscope.migrations", "MYDB", "Myscope"})
	if err != nil {
		log.Fatal(err)
	}

	m, err := migrate.NewWithDatabaseInstance("file:///migrations", "sqlserver", instance)
	if err != nil {
		return errors.Wrap(err, "failed to create new migration")
	}

	err = m.Steps(1)
	if err != nil {
		return errors.Wrap(err, "failed to make steps")
	}`

this code gives me the error:
`panic: sql: Register called twice for driver mssql

goroutine 1 [running]:
database/sql.Register(0x18b61e9, 0x5, 0x19db5e0, 0x20c9130)
        /usr/local/Cellar/go/1.12.7/libexec/src/database/sql/sql.go:51 +0x189
github.com/denisenkom/go-mssqldb.init.1()
        /Users/user/go/src/github.com/denisenkom/go-mssqldb/mssql.go:32 +0x52`

if i'm using it without importing  _ "github.com/denisenkom/go-mssqldb":

`panic: database migrations error: failed to create new migration: source driver: unknown driver file (forgotten import?)
`
