### ISSUE TITLE
Getting "error: file does not exist"  

### ISSUE THREAD

**Issue by nutmix** [golang-migrate/migrate#79] opened 2018-07-31 23:41 UTC
We have run the migration successfully, and now i need to run it again in case there are any new migrations.

This is he command we are using:

migrate -database 'mysql://xxx:yyyy@/zzzz' -source file://go/src/github.com/me/myproj.org/db/schema up

I am in the root directory of the user (i.e. /home/myuser), and underneath is the structure:
go/src/github.com/me/myproj.org/db/schema which contains files like:

201802221525_init_schema.down.sql  201805211743_us_states.down.sql  201805291420_countries.down.sql  201806051200_currencies.down.sql
201802221525_init_schema.up.sql    201805211743_us_states.up.sql    201805291420_countries.up.sql    201806051200_currencies.up.sql
etc.

We see that with mattes migrate, there were many similar issues with no obvious resolution.

in the db in schema_migrations table, I see it says version 201807191200, although i am not sure this has any bearing on the issue.

If I change the file path to something which doesn't exist, e.g.

migrate -database 'mysql://xxx:yyyy@/zzzz' -source file://go/src/github.com/me/myproj.org/notexist up

I get a different error message:

error: open /home/muyuser/go/src/github.com/me/myproj.org/notexist : no such file or directory

This is how we installed migrate:

wget https://github.com/golang-migrate/migrate/releases/download/v3.2.0/migrate.linux-amd64.tar.gz 
gunzip migrate.linux-amd64.tar.gz 
tar xvf migrate.linux-amd64.tar
mv migrate.linux-amd64 /usr/bin/migrate

**Comment by nutmix** [comment] 2018-08-01 08:39
This error might be occurring when the DB is up to date, i.e. no migrations needed.  However, if so, its still a bug as it should say up to date, not error.

**Comment by dotchev** [comment] 2018-08-03 15:09
If it is up to date, you will get a different error - "no change".

I get "file does not exist" error when I accidentally delete some of my migration scripts, e.g. switching between git branches.
Here is an example with some added trace messages:
```
versionExists: version 2
versionExists: ReadUp error: read version 2 .../storage/postgres/migrations: file does not exist
versionExists: ReadDown error: read version 2 .../storage/postgres/migrations: file does not exist
versionExists: fallthrough - os.ErrNotExist
PANI[0000] file does not exist 
```
But in that directory there are scripts only for version 1
```
$ ls storage/postgres/migrations
001_initial_schema.down.sql
001_initial_schema.up.sql
```
During debugging I see [versionExists](https://github.com/golang-migrate/migrate/blob/master/migrate.go#L756) returns `os.ErrNotExist` (message "file does not exist") instead of the original error message (printed above).

It will be much easier to troubleshoot, if the original error with descriptive message is returned.

**Comment by francisdb** [comment] 2018-08-17 11:54
is this a duplicate of #35?

**Comment by Kigamba** [comment] 2019-04-21 12:05
Any solution on this issue?? I need to run the migrations every time the application starts. I keep getting this error if the migrations are up-to-date

**Comment by justty** [comment] 2019-04-21 13:41
I have this problem on windows,  but on linux its worked. I think it's related with the docker volume.

docker-compose.yml
```
version: '3.6'
services:
  db:
    image: postgres:11.2
    restart: always
    container_name: db
    networks:
      - db-network
    ports:
      - 5432:5432
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  db_migrations:
    image: migrate/migrate
    container_name: db_migrations
    networks:
      - db-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    command: -path=/migrations -database postgres://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME?sslmode=disable up
```

**Comment by dhui** [comment] 2019-04-30 22:55
Are people still hitting this issue with migrate [v4.3.1](https://github.com/golang-migrate/migrate/releases/tag/v4.3.1)?
If so, please provide the error message(s) and the list of migration files. e.g. info on how to reproduce the issue

**Comment by ansel1** [comment] 2019-05-20 19:55
Yes, I just experienced it.  The only error message (the only output at all) is "error: file does not exist".  Even in verbose mode.

To reproduce, create a db and a migrate, apply the migration to the db, then delete the migration and create a new, different migration, and try to apply that.  I think migrate is looking for migrations files which match the database's record of applied migrations.

**Comment by AntonMSova** [comment] 2019-05-23 03:36
I'm experiencing the same issue on[ v4.3.1](https://github.com/golang-migrate/migrate/releases/tag/v4.3.1). There is no other error than `file does not exist"`. The problem is in `versionExists` function. It returns `os.ErrNotExist` error,  and it's caught . inside `readUp` function:
`	if from >= 0 {
		if err := m.versionExists(suint(from)); err != nil {
			ret <- err
			return
		}
	}
`

So running 2 migrations: 
`1_schema.up.sql
2_seed.up.sql` 
that are in the same folder works. But put them in separate folders and run these two migrations separately, then the second one will return `file does not exist` error.

**Comment by dhui** [comment] 2019-05-27 20:34
@ansel1 
> To reproduce, create a db and a migrate, apply the migration to the db, then delete the migration and create a new, different migration, and try to apply that. I think migrate is looking for migrations files which match the database's record of applied migrations.

Before deleting a migration from the source, you need to run the down migration for it to keep your schema sane and update `migrate`'s bookkeeping.


@AntonMSova 
> So running 2 migrations: `1_schema.up.sql` `2_seed.up.sql` that are in the same folder works. But put them in separate folders and run these two migrations separately, then the second one will return file does not exist error.

Migrations need to be in the same folder/directory. Currently, the file source driver doesn't support recursing into directories.

**Comment by AntonMSova** [comment] 2019-05-27 21:04
@dhui 
are there any plans to add an option to skip migration file check and just compare versions?
I'm running multiple apps that share many tables. So I need run schema migrations once and later on seed database based on the app I'm running. So currently I just include an empty migration with the version of last successful migration in my seed directories just to pass the file check. An option to be able to run a migration with a higher version without file check of a current version would save me from keeping all those empty files and version matching. Then there is no need for recursing into directories, just check the version of a running migration with the current one and if it is higher - migrate. Then it will be possible to run migrations from different sources. For example keep tables schema in Google Cloud Storage and seed for each app in their gitlab repos.

**Comment by dhui** [comment] 2019-05-28 01:48
@AntonMSova 
> I'm running multiple apps that share many tables.

`migrate` is designed to be simple and safe, so there won't be an option to skip migration file checking. Instead, I suggest you restructure how you manage your migrations. You could either:
1. Pick certain apps to own certain tables
1. Have a single app manage all of your tables/migrations
    * This approach is probably simpler at small scale

If you'd like to continue discussing this, please open a separate issue.

**Comment by ansel1** [comment] 2019-05-28 02:03
I agree it was user error. The error message is very opaque though. I didn’t realize at first that my migrations we’re out of sync, and I was banging my keyboard for a while before coming across this thread and realizing what I’d done. A better error or more debug output could help.

**Comment by ywk253100** [comment] 2019-08-28 03:48
We got the same error when running migration.

We maintains 2 versions of an application: 
v1.0 released with 10_schema.up.sql
v2.0 released with 10_schema.up.sql and 20_schema.up.sql

We found a bug in v1.0 and fixed it by changing database schema, so we released v1.1 with 10_schema.up.sql and 11_schema.up.sql.

But when users trying to upgrade v1.1 to v2.0, we got the "file does not exist" error as there is no 11_schema.up.sql in release v2.0. How can we handle this? Does checking the existence of 11_schema.up.sql make sense?

**Comment by dhui** [comment] 2019-08-29 04:42
@ywk253100 Assuming you can detect when an upgrade occurs, you can either:
1. Force the migration. e.g. set the last successful migration to 10_schema.up.sql before running the v2.0 migrations
1. Apply an upgrade migration. e.g. a set of migrations that contains the last v1.1 migration, missing migration(s) and the first v2.0 migration.

Neither solution is great since (1) is dangerous if a failure occurs during the migration and (2) makes it hard to maintain migrations. Unfortunately, `migrate` isn't as sophisticated as `git` where you can merge branches of migrations. Currently, migrations are expected to be linear.

Did you come up with other solutions?

This seems like a separate issue. Could you open a new one with a title along the lines of "support non-linear migrations`?

**Comment by ywk253100** [comment] 2019-08-30 03:00
Opened #278 to track the non-linear migrations.
Our solution for now is that for v1.x only releases with 10_schema.up.sql, any other changes in sub version are handled by our own logic

**Closed** 2019-08-30 03:09 UTC

**Comment by rajeshnair** [comment] 2019-12-19 11:44
> @ansel1
> 
> > To reproduce, create a db and a migrate, apply the migration to the db, then delete the migration and create a new, different migration, and try to apply that. I think migrate is looking for migrations files which match the database's record of applied migrations.
> 
> Before deleting a migration from the source, you need to run the down migration for it to keep your schema sane and update `migrate`'s bookkeeping.
> 
> @AntonMSova
> 
> > So running 2 migrations: `1_schema.up.sql` `2_seed.up.sql` that are in the same folder works. But put them in separate folders and run these two migrations separately, then the second one will return file does not exist error.
> 
> Migrations need to be in the same folder/directory. Currently, the file source driver doesn't support recursing into directories.

@dhui 
It is not about just recursing the directories
Our use-case is 2 or more microservices needing the capability to migrate on their own.
microserviceA with 01_schema_init.up.sql works fine in scripts/sql
but microserviceB fails 

I have tried naming the microserviceB script as 01 or 02 but it still fails.

Also think of scenarios where the sql scripts are inside the docker image.

**Comment by ansel1** [comment] 2019-12-19 19:47
@rajeshnair quick workaround for your case would be storing the different lineage's of migrations in different tables.  There is an option to use a different migration history table.

**Comment by rajeshnair** [comment] 2019-12-20 08:22
@ansel1 

Yes, that's what I did and it solved my use-case.
In fact , having seperate migration tables for each microservice makes sense as they would evolve seperately.

If there is any way I can help with documenting this, it would be of help.

**Comment by dhui** [comment] 2020-01-03 05:45
Yeah, keeping migrations separate for each app is a best practice. We could document this in the [FAQ](https://github.com/golang-migrate/migrate/blob/master/FAQ.md) or [MIGRATIONS](https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md). In general, the docs could be re-organized... Any help is greatly appreciated! 🙏

**Comment by singhmj** [comment] 2020-05-05 05:21
In my case, I missed the file naming convention and named migration file as `1_initial_up.sql` but it worked as soon as I fixed it to `1_initial.up.sql`.

**Comment by viettd** [comment] 2020-12-01 07:44
> In my case, I missed the file naming convention and named migration file as `1_initial_up.sql` but it worked as soon as I fixed it to `1_initial.up.sql`.

I have the same mistake. Thank a lot 🙏

**Comment by adrianbompa** [comment] 2021-08-06 11:42
I had similar issue,  but mine was caused by the fact that I was using `m.Steps(3)` rather than `m.Migrate(3)`

**Comment by hellojack123** [comment] 2022-01-27 07:20
I also encountered this error. I wrote the wrong file name

**Comment by joshhrrsn** [comment] 2022-03-30 16:20
In case this helps anyone out - the migrations are referenced in the table `schema_migrations`. You can always find the bad reference in there and remove it (and any rows created after it) and then re-run your `up` migrations. 

I did this working with a local DB and it resolved my issue, if you're dealing with an actual db instance with important data then obviously use with caution!

**Comment by buryo** [comment] 2022-09-17 15:14
In my case I was not in the right (migrations) folder #plamFace.

**Comment by normatov07** [comment] 2022-10-20 11:35
I have the same error. How can I fix this ?

**Comment by imanaspaul** [comment] 2022-10-29 15:38
steps to fix the issue,  go to your database and check the last version of your migration at schema_migrations table

```sh
migrate -path migrations/ -database postgres://test:test@localhost/dummy?sslmode=disable force [increament your version]
```
then run the migration comman again, it will work.

**Comment by KanhaiyaKumarGupta** [comment] 2023-11-17 14:00
migrate -path db/migration -database "postgresql://root:password@localhost:5432/simple_bank?sslmode=disable" -verbose up 2023/11/17 18:56:27 error: no migration found for version 0: read down for version 0 .: file does not exist
2023/11/17 18:56:27 error: no migration found for version 0: read down for version 0 .: file does not exist
how to fix this

**Comment by Nicolas-ggd** [comment] 2024-03-08 10:07
> .

When i run following command i got error: 
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reset OCSP cache file. /home/yamato/.cache/snowflake/ocsp_response_cache.json 
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reading OCSP Response cache file. /home/yamato/.cache/snowflake/ocsp_response_cache.json 
ERRO[0000]log.go:120 gosnowflake.(*defaultLogger).Errorf failed to open. Ignored. open /home/yamato/.cache/snowflake/ocsp_response_cache.json: no such file or directory

How can i fix this error? it seems like migration can't see Errorf file to open it

**Comment by creotiv** [comment] 2024-10-30 20:15
JFYI if in path exist symbol `-` - it will give such error

**Comment by mattrltrent** [comment] 2025-01-26 06:17
Just migrate down then back up. That's what worked for me.
