### ISSUE TITLE
migrate mysql failure should have started in transaction without the need for dirty

### ISSUE THREAD

**Issue by u007** [golang-migrate/migrate#453] opened 2020-10-06 13:03 UTC
**Describe the Bug**

when running migration, if any part fail, it should not need to trigger dirty =1
and it should rollback for mysql

**Steps to Reproduce**
1. add migration with missing  field to drop
2. migrate should fail 
3. schema migration now has latest failed migration number and dirty=1

**Expected Behavior**
migration should not up the migration number and dirty donot need to be set

**Migrate Version**
4.11.0
**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
Source drivers: s3, github, github-ee, gitlab, go-bindata, godoc-vfs, gcs, file
Database drivers: cassandra, cockroachdb, crdb-postgres, firebirdsql, postgresql, clickhouse, firebird, postgres, mongodb, mysql, redshift, spanner, cockroach, sqlserver, stub

**Go Version**
none

**Comment by dhui** [comment] 2020-10-06 21:03
Duplicate of https://github.com/golang-migrate/migrate/issues/196

**Closed by dhui** 2020-10-06 21:03 UTC
Labels: duplicate
