### ISSUE TITLE
Support go migrations

### ISSUE THREAD

**Issue by denismakogon** [golang-migrate/migrate#18] opened 2018-04-17 17:02 UTC
SQL migrations is a good thing, but likely useless in many cases. Migrate must support go migrations, i.e a function that accepts an instance of the database or a transaction object (in case of SQL datastores).
Something along the lines of this to up the version:
```go
func up(tx *sql.Tx) error {
         _, err := tx.Exec("ALTER TABLE calls ADD stats text;")
	return err
}
```
down also looks the same:
```go
func down(tx *sql.Tx) error {
	_, err := tx.Exec("ALTER TABLE calls DROP COLUMN stats;")
	return err
}
```
original issue: https://github.com/mattes/migrate/issues/344

**Comment by dhui** [comment] 2018-04-17 17:54
Duplicate of https://github.com/golang-migrate/migrate/issues/15
Use that issue for discussion

**Closed by dhui** 2018-04-17 17:54 UTC
