### ISSUE TITLE
Manipulating data with Go

### ISSUE THREAD

**Issue by besedad** [golang-migrate/migrate#243] opened 2019-07-01 06:12 UTC
I'm very new to the whole concept of the migration. I was wondering if it's possible to use the package to manipulate data in postgres tables, not just the schema, but data itself, using Go code. By manipulate I mean to transform them from one format to another; and by Go code I mean a function that runs for given `migrate.Migrate` and has access to the data.

I suppose this could be done in some hacky fashion, glue everything together, but I'm looking more for a systemic approach that leverages abstractions (i.e. source Driver) already found in the package.

What would be the proper way to implement such thing? Lack of examples and general documentation makes me think that either this isn't relevant to the concept of *migration* or the logic has to be implemented around the package. Another possibility is that the code base that I've inherited, which happens to use your package, is rigidly designed, not accounting for such eventuality.

**Comment by dhui** [comment] 2019-07-01 15:50
Duplicate of: https://github.com/golang-migrate/migrate/issues/15

Please continue any discussions regarding support for migrations written in Go in the original issue.

For your specific needs, I'd implement as much of the data migrations you can in SQL. But if there's more complicated logic that's hard or impossible to express in SQL (or whatever your migrations are written in), `migrate` does not support migrations written in Go or Bash. e.g. if you need repeatable and reversable migrations written in Go, `migrate` won't be of much use right now.

**Closed** 2019-12-16 07:42 UTC
