### ISSUE TITLE
Missing timezone info in Docker image

### ISSUE THREAD

**Issue by georgantasp** [golang-migrate/migrate#201] opened 2019-04-04 16:29 UTC
**Describe the Bug**
When using the docker image against ClickHouse:
```
$ docker run -v `pwd`/migrations:/migrations/ migrate/migrate -path=/migrations/ -database clickhouse://[HOST]:9000/ up
```
I'm getting the error:
```
error: could not load time location: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
```
This is may be related to the clickhouse db driver.

I can fix the issue in an interactive session by installing the `tzdata` package:
```
$ docker run -it --entrypoint "/bin/sh" -v `pwd`/migrations:/migrations/ migrate/migrate
# /migrate -path=/migrations/ -database clickhouse://[HOST]:9000/ up
error: could not load time location: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
# apk add tzdata
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tzdata (2018i-r0)
Executing busybox-1.29.3-r10.trigger
OK: 10 MiB in 16 packages
# /migrate -path=/migrations/ -database clickhouse://[HOST]:9000/ up
no change
```

**Steps to Reproduce**
See above. One caveat is that I could not reproduce the issue against a dockerized clickhouse server. The issue only arose when running against an install in AWS.

**Expected Behavior**
Docker image expected to be built with all necessary dependencies for migrate.

**Migrate Version**
```
# /migrate -version
v4.2.5
```

**Loaded Source Drivers**
```
# /migrate -help
...
Source drivers: s3, github, go-bindata, gcs, file

```

**Loaded Database Drivers**
```
# /migrate -help
...
Database drivers: crdb-postgres, mysql, postgresql, stub, cassandra, cockroachdb, mongodb, postgres, redshift, spanner, clickhouse, cockroach
```

**Go Version**
N/A: go is not installed on the base image (alpine:3.9) by design.

**Stacktrace**
Please provide if available

**Additional context**

**Comment by dhui** [comment] 2019-04-05 02:15
I'm not sure what the best solution for this issue is.

I'm hesitant about adding a timezone file to the docker image since timezones are constantly being updated. I'd like old images to use current timezone data.

Workarounds:
1. Mount your system's timezone as the timezone file for the running container
1. Build your own image from migrate and pull in the timezone file
1. ???

**Comment by georgantasp** [comment] 2019-04-05 14:54
Thanks for quick response.

I actually hadn't thought of that, but I completely agree with your point. I did end up building my own image for this and to add other functionality. However, I will look at mounting the host file to avoid the tz issue altogether.

There's probably another cause/solution through the clickhouse integration, but that seems like a bigger rabbit hole.

Thanks again.

**Comment by dhui** [comment] 2020-09-13 22:14
Closing as there's no solution for `migrate` to implement

**Closed by dhui** 2020-09-13 22:14 UTC

**Comment by dhui** [comment] 2020-10-01 05:12
FYI, in Go 1.15, you can now [embed tz data as a fallback](https://golang.org/doc/go1.15#time/tzdata)

**Comment by fzyzcjy** [comment] 2022-04-14 12:21
I find some systems **do not have** timezone data. For example, in my `k3d` (`k3s`) cluster, the "host" machine (indeed, just another docker container by design) has a completely empty `/usr/share/zoneinfo` folder. 

Thus, embed tz data sounds reasonable.

**Comment by sebcoetzee** [comment] 2024-01-25 11:06
Ran into this issue with migrations on Clickhouse. Mounting system's timezone directory fixed the issue as described in https://github.com/golang-migrate/migrate/issues/201#issuecomment-480125730.

```
docker run --rm --volume /usr/share/zoneinfo:/usr/share/zoneinfo:ro migrate/migrate:4 <my arguments>
```
