### ISSUE TITLE
Can not insert data type datetime in mongodb

### ISSUE THREAD

**Issue by buicongtan1997** [golang-migrate/migrate#535] opened 2021-03-30 03:56 UTC
**Describe the Bug**
I can not insert documents in migration stage, it has field `created_at, updated_at` which data type is date.

**Steps to Reproduce**
1. My migrations look like 
```json
[
  {
   "insert": "roles",
   "documents": [
      {
        "_id": "root1",
        "name": "Root1",
        "created_at": {"$date": "2021-03-24T08:15:28.716Z"},
        "updated_at": {"$date": "2021-03-24T08:15:28.716Z"}
      }
   ]
  }
]
``` 
3. See error
`migrate_1         | error: unmarshaling json error: invalid JSON input; expected {`

**Expected Behavior**
can insert document with data type datetime
**Migrate Version**
v4.14.1

Obtained by running: `migrate -version`

**Loaded Source Drivers**
 file

**Loaded Database Drivers**
mongodb

**Comment by dhui** [comment] 2021-04-05 05:42
I'm not familiar with MongoDB. Are you able to run the same query outside of migrate. e.g. via the mongdb CLI and directly via the Go mongodb driver?

**Comment by nandosola** [comment] 2021-06-04 11:32
Hi,

I can confirm this is not a bug. The error ` error: unmarshaling json error: invalid JSON input;…` is emitted by the driver's `bson.UnmarshallExternalJSON`

https://github.com/golang-migrate/migrate/blob/2c2f6910f4f72ba862c5c93811e41a7db7320f24/database/mongodb/mongodb.go#L231-L234

This means, the migration must be formatted in [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/), which for ISODate fields just works with:

```
  "createdAt": { "$date": { "$numberLong": "{unix_tstamp}" }}
```

It seems the canonical strict format is no longer `"$date": "<ISO-8601>"`, so `$date` must me an object. Which is exactly what the error complains about.

**Comment by Fontinalis** [comment] 2021-08-23 13:27
Based on @nandosola comment, I'm closing this issue, since it was an error in the migration and not in `migrate` itself. For additional questions, please reopen it or submit a new issue.

**Closed by Fontinalis** 2021-08-23 13:27 UTC
